-- require('nvim-treesitter').setup({
--   ensure_installed = { "bash", "typescript", "javascript", "c", "lua", "vim", "vimdoc", "query", "php" },
--   sync_install = false,
--   auto_install = false,
-- })
