#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/wizetux/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

conky -p 3 &
nitrogen --restore &
# ${HOME}/xplanet/xplanet_bg.sh &
xscreensaver -no-splash &
eval $(ssh-agent)
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/wizetux/.fluxbox/log"
# eval SSH_AUTH_SOCK=/tmp/ssh-36Mj33hSpI5O/agent.1154; export SSH_AUTH_SOCK;
# SSH_AGENT_PID=1155; export SSH_AGENT_PID;
